http:
  host: 'localhost'
  port: 3000

database:
  url: 'localhost:27017'
  name: 'ack'
  user: ''
  password: ''

app:
  env: 'development'
  language: 'en'
  debug: false
  encryption:
    encrypt: false
    key: 'NRsycc8LAYc0gShCIzU4hZiFDH4Xc1dO'
    iv: 'JAPgKqVkC7aUsE4x'
  
  logger: 
    http: false
    system: false

  pagination: 
    page: 1
    limit: 10

  hash: 
    passwordLatLength: 16

  auth:
    usernameField: 'email'
    jwtSecretKey: '9UbQX7iQvgaW4Bm7HwzU'
    jwtExpiration: '1h'
    basicClientId: 'rw0sOzrpMP2CpQqXozZsjk5AI5cL00uyDIUiN0gn'
    basicClientSecret: '275tqa6S4sWCyBHBvFezJJm0QRvxK39VOgLOTXVo'
