http:
  host: 'localhost'
  port: 3000

database:
  url: 'localhost:27017'
  name: 'ack'
  user: ''
  password: ''

app:
  env: 'development'
  language: 'en'
  debug: true

  pagination: 
    page: 1
    limit: 10

  hash: 
    passwordLatLength: 16

  auth:
    usernameField: 'email'
    jwtSecretKey: '9UbQX7iQvgaW4Bm7HwzU'
    jwtExpiration: 3600000
    basicTokenClientId: 'rw0sOzrpMP2CpQqXozZsjk5AI5cL00uyDIUiN0gn'
    basicTokenClientSecret: '275tqa6S4sWCyBHBvFezJJm0QRvxK39VOgLOTXVo'
