version: "3.6"
services:
  nest:
    build:
      context: .
      dockerfile: dockerfile
    container_name: ack
    environment:
      - NODE_ENV=development
    volumes:
      - config.yml:/app/config.yml
    ports:
      - 3000:3000